- name: nvim
  repo: git@github.com:kamuridesu/nvim-config.git
- name: fish
  repo: git@github.com:kamuridesu/peixefiles.git
- name: dotsyncer
  repo: git@github.com:kamuridesu/dotsfile.git
- name: rofi
  repo: git@github.com:kamuridesu/rofi-config.git
